# Generated by Django 5.2.11 on 2026-06-09 13:57

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Buyruq raqami')),
                ('order_type', models.CharField(choices=[('hiring', 'Ishga qabul qilish'), ('transfer', "Boshqa lavozimga o'tkazish"), ('termination', 'Mehnat shartnomasini bekor qilish'), ('promotion', "Rag'batlantirish"), ('disciplinary', 'Intizomiy jazo'), ('leave', "Ta'til"), ('temporary_duty', 'Vaqtincha vazifa yuklash'), ('salary_change', "Oylik o'zgartirish")], max_length=20, verbose_name='Buyruq turi')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Buyruq sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Tasdiqlanmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holat')),
                ('legal_basis', models.TextField(blank=True, help_text='Mehnat kodeksi moddalari, arizalar va boshqa asoslar', verbose_name='Asos')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to='employees.employee', verbose_name='Tasdiqlovchi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Buyruq',
                'verbose_name_plural': 'Buyruqlar',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiringOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('contract_type', models.CharField(choices=[('indefinite', 'Nomuayyan muddatga'), ('fixed_term', 'Muayyan muddatga')], default='indefinite', max_length=20, verbose_name='Shartnoma turi')),
                ('start_date', models.DateField(verbose_name='Ish boshlash sanasi')),
                ('end_date', models.DateField(blank=True, help_text='Faqat muayyan muddatli shartnoma uchun', null=True, verbose_name='Tugash sanasi')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Oylik maosh')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Masalan: 0.5, 1.0, 1.5', max_digits=3, verbose_name='Stavka')),
                ('work_schedule', models.CharField(choices=[('full_time', "To'liq ish kuni"), ('part_time', "To'liqsiz ish kuni"), ('part_week', "To'liqsiz ish haftasi")], default='full_time', max_length=20, verbose_name='Ish tartibi')),
                ('has_probation', models.BooleanField(default=False, verbose_name='Sinov muddati bor')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='Sinov muddati tugash sanasi')),
                ('probation_salary', models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qolsa asosiy oylik olinadi", max_digits=15, null=True, verbose_name='Sinov muddati oyligi')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='Mehnat shartnomasi raqami')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Mehnat shartnomasi sanasi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name="Bo'lim")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_order_items', to='employees.employee', verbose_name='Xodim')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.position', verbose_name='Lavozim')),
                ('probation_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_hiring_items', to='departments.department', verbose_name="Sinov muddati bo'limi")),
                ('probation_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_hiring_items', to='employees.position', verbose_name='Sinov muddati lavozimi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_items', to='orders.order', verbose_name='Buyruq')),
            ],
            options={
                'verbose_name': 'Ishga olish qatori',
                'verbose_name_plural': 'Ishga olish qatorlari',
                'ordering': ['id'],
            },
        ),
    ]
