# Generated by Django 5.2.15 on 2026-06-09 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=100, verbose_name="Bo'lim nomi")),
                ('code', models.CharField(max_length=20, unique=True, verbose_name="Bo'lim kodi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name="Bo'lim boshlig'i")),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='departments.department', verbose_name="Yuqori bo'lim")),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['name'],
            },
        ),
    ]
