[program:hr-pro]
command=/var/www/hr-pro/venv/bin/gunicorn config.wsgi:application -c /var/www/hr-pro/gunicorn.conf.py
directory=/var/www/hr-pro
user=deploy
numprocs=1
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
stdout_logfile=/var/log/hr-pro/supervisor.log
stderr_logfile=/var/log/hr-pro/supervisor_error.log
environment=DJANGO_SETTINGS_MODULE="config.settings.prod"
