# Generated by Django 5.2.15 on 2026-06-09 10:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('category', models.CharField(choices=[('annual', "Yillik ta'til"), ('sick', 'Kasallik varaqasi'), ('unpaid', "To'lanmaydigan ta'til"), ('maternity', "Ona ta'tili"), ('paternity', "Ota ta'tili"), ('study', "O'quv ta'tili"), ('other', 'Boshqa')], default='annual', max_length=20, verbose_name='Kategoriya')),
                ('default_days', models.PositiveSmallIntegerField(default=15, verbose_name='Standart kunlar (yillik)')),
                ('max_days', models.PositiveSmallIntegerField(default=30, verbose_name='Maksimal kunlar')),
                ('min_days', models.PositiveSmallIntegerField(default=1, verbose_name='Minimal kunlar')),
                ('is_paid', models.BooleanField(default=True, verbose_name="To'lanadimi")),
                ('requires_document', models.BooleanField(default=False, verbose_name='Hujjat talab qilinadimi')),
                ('can_be_carried_forward', models.BooleanField(default=True, verbose_name="Keyingi yilga o'tkazilishi mumkinmi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Ta'til turi",
                'verbose_name_plural': "Ta'til turlari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('requested_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name="So'ralgan kunlar")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holat')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_documents/%Y/%m/', verbose_name='Hujjat')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee', verbose_name='Tasdiqlagan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Xodim')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype', verbose_name="Ta'til turi")),
            ],
            options={
                'verbose_name': "Ta'til so'rovi",
                'verbose_name_plural': "Ta'til so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('entitled_days', models.DecimalField(decimal_places=1, default=Decimal('15'), max_digits=5, verbose_name='Berilgan kunlar')),
                ('carried_forward', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name="O'tkazilgan kunlar")),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='Ishlatilgan kunlar')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='Xodim')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype', verbose_name="Ta'til turi")),
            ],
            options={
                'verbose_name': "Ta'til balansi",
                'verbose_name_plural': "Ta'til balanslari",
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
