# Generated by Django 5.2.11 on 2026-06-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='default_days',
            field=models.PositiveSmallIntegerField(default=21, verbose_name='Standart kunlar (yillik)'),
        ),
    ]
