# Generated by Django 5.2.11 on 2026-06-09 12:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Kelish vaqti')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Ketish vaqti')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kechikdi'), ('half_day', 'Yarim kun'), ('on_leave', "Ta'tilda"), ('sick', 'Kasallik'), ('business_trip', 'Xizmat safari')], default='present', max_length=20, verbose_name='Holat')),
                ('work_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Ish soatlari')),
                ('late_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Kechikish (daqiqa)')),
                ('early_leave_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Erta ketish (daqiqa)')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Xodim')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Oy')),
                ('work_days', models.PositiveSmallIntegerField(default=0, verbose_name='Ish kunlari (rejadagi)')),
                ('present_days', models.PositiveSmallIntegerField(default=0, verbose_name='Kelgan kunlar')),
                ('absent_days', models.PositiveSmallIntegerField(default=0, verbose_name='Kelmagan kunlar')),
                ('late_days', models.PositiveSmallIntegerField(default=0, verbose_name='Kechikkan kunlar')),
                ('leave_days', models.PositiveSmallIntegerField(default=0, verbose_name="Ta'til kunlari")),
                ('sick_days', models.PositiveSmallIntegerField(default=0, verbose_name='Kasallik kunlari')),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Jami ish soatlari')),
                ('total_late_minutes', models.PositiveIntegerField(default=0, verbose_name='Jami kechikish (daqiqa)')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('confirmed', 'Tasdiqlangan')], default='draft', max_length=20, verbose_name='Holat')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_timesheets', to='employees.employee', verbose_name='Tasdiqlagan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Oylik tabel',
                'verbose_name_plural': 'Oylik tabellar',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
