# Generated by Django 5.2.15 on 2026-06-09 07:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=50, verbose_name='Davr nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('processing', 'Hisoblanmoqda'), ('confirmed', 'Tasdiqlangan'), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holat')),
                ('work_days', models.PositiveSmallIntegerField(default=22, verbose_name='Ish kunlari')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
            ],
            options={
                'verbose_name': 'Ish haqi davri',
                'verbose_name_plural': 'Ish haqi davrlari',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('component_type', models.CharField(choices=[('earning', "Qo'shimcha (hisoblash)"), ('deduction', 'Ushlanma (ayirish)')], max_length=20, verbose_name='Turi')),
                ('calculation_type', models.CharField(choices=[('fixed', "Qat'iy summa"), ('percentage', 'Foiz (bazadan)'), ('formula', 'Formula')], default='fixed', max_length=20, verbose_name='Hisoblash usuli')),
                ('default_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Standart qiymat')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Soliqqa tortiladimi')),
                ('is_statutory', models.BooleanField(default=False, verbose_name='Qonuniy (JSHDT, INPS)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Ish haqi komponenti',
                'verbose_name_plural': 'Ish haqi komponentlari',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('calculated', 'Hisoblangan'), ('confirmed', 'Tasdiqlangan'), ('paid', "To'langan")], default='draft', max_length=20, verbose_name='Holat')),
                ('work_days', models.PositiveSmallIntegerField(default=0, verbose_name='Ishlangan kunlar')),
                ('absent_days', models.PositiveSmallIntegerField(default=0, verbose_name='Kelmaган kunlar')),
                ('leave_days', models.PositiveSmallIntegerField(default=0, verbose_name="Ta'til kunlari")),
                ('sick_days', models.PositiveSmallIntegerField(default=0, verbose_name='Kasallik kunlari')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Asosiy ish haqi')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Yalpi ish haqi')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name="Jami qo'shimchalar")),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Jami ushlanmalar')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Sof ish haqi')),
                ('jshdt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='JSHDT')),
                ('inps_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='INPS')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='Xodim')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrollperiod', verbose_name='Davr')),
            ],
            options={
                'verbose_name': 'Ish haqi',
                'verbose_name_plural': 'Ish haqlari',
                'ordering': ['-period__start_date', 'employee__employee_code'],
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Summa')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payroll', verbose_name='Ish haqi')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarycomponent', verbose_name='Komponent')),
            ],
            options={
                'verbose_name': 'Ish haqi elementi',
                'verbose_name_plural': 'Ish haqi elementlari',
                'ordering': ['component__component_type', 'component__name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('jshdt', "JSHDT (Daromad solig'i)"), ('jshdt_it', 'JSHDT (IT Park)'), ('inps', 'INPS (Pensiya fondi)'), ('social', 'Ijtimoiy soliq')], max_length=20, verbose_name='Soliq turi')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Stavka (%)')),
                ('effective_date', models.DateField(verbose_name='Kuchga kirish sanasi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Soliq stavkasi',
                'verbose_name_plural': 'Soliq stavkalari',
                'ordering': ['-effective_date', 'tax_type'],
                'unique_together': {('tax_type', 'effective_date')},
            },
        ),
    ]
