# Generated by Django 5.2.15 on 2026-06-09 07:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Entry-level specialist'), (2, 'Level 2 - Junior specialist'), (3, 'Level 3 - Mid-level specialist'), (4, 'Level 4 - Independent specialist'), (5, 'Level 5 - Experienced specialist'), (6, 'Level 6 - Highly qualified specialist'), (7, 'Level 7 - Senior specialist'), (8, 'Level 8 - Lead specialist'), (9, 'Level 9 - Principal lead specialist'), (10, 'Level 10 - Chief specialist')], unique=True, verbose_name='Daraja')),
                ('name', models.CharField(max_length=100, verbose_name='Daraja nomi')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Koeffitsiyent')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Daraja',
                'verbose_name_plural': 'Darajalar',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='MHTMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(unique=True, verbose_name='Kuchga kirish sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="MHTM miqdori (so'm)")),
                ('decree_number', models.CharField(blank=True, max_length=50, verbose_name='Qaror raqami')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MHTM tarixi',
                'verbose_name_plural': 'MHTM tarixi',
                'ordering': ['-effective_date'],
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.CreateModel(
            name='TenureBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('min_months', models.PositiveIntegerField(verbose_name='Minimum oylar')),
                ('max_months', models.PositiveIntegerField(blank=True, help_text="Bo'sh qoldirilsa - cheksiz", null=True, verbose_name='Maksimum oylar')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Koeffitsiyent')),
            ],
            options={
                'verbose_name': 'Staj koeffitsiyenti',
                'verbose_name_plural': 'Staj koeffitsiyentlari',
                'ordering': ['min_months'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=100, verbose_name='Lavozim nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Lavozim kodi')),
                ('base_coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Bazaviy koeffitsiyent')),
                ('description', models.TextField(blank=True, verbose_name='Lavozim tavsifi')),
                ('requirements', models.TextField(blank=True, verbose_name='Talablar')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='departments.department', verbose_name="Bo'lim")),
                ('max_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_positions', to='employees.level', verbose_name='Maksimal daraja')),
                ('min_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_positions', to='employees.level', verbose_name='Minimal daraja')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='Xodim kodi')),
                ('contract_type', models.CharField(choices=[('permanent', 'Doimiy'), ('fixed_term', 'Muddatli'), ('probation', 'Sinov muddati'), ('part_time', 'Yarim stavka')], default='permanent', max_length=20, verbose_name='Shartnoma turi')),
                ('hire_date', models.DateField(verbose_name='Ishga kirgan sana')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Shartnoma tugash sanasi')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='Sinov muddati tugashi')),
                ('prior_experience_months', models.PositiveIntegerField(default=0, verbose_name='Oldingi ish staji (oylar)')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('on_leave', "Ta'tilda"), ('suspended', "To'xtatilgan"), ('terminated', "Ishdan bo'shatilgan")], default='active', max_length=20, verbose_name='Holat')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name="Ishdan bo'shatilgan sana")),
                ('termination_reason', models.TextField(blank=True, verbose_name="Ishdan bo'shatilish sababi")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department', verbose_name="Bo'lim")),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Bevosita rahbar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.level', verbose_name='Daraja')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position', verbose_name='Lavozim')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['employee_code'],
            },
        ),
    ]
