# Generated by Django 5.2.11 on 2026-06-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('on_leave', "Ta'tilda"), ('suspended', "To'xtatilgan"), ('terminated', "Ishdan bo'shatilgan")], default='active', max_length=20, verbose_name='Holat'),
        ),
    ]
